### ISSUE TITLE
issue with installing msys

### ISSUE THREAD

**Issue by frdyli** [nus-cs2030/2324-s2#4] opened 2024-01-15 05:12 UTC
<img width="468" alt="issue" src="https://github.com/nus-cs2030/2324-s2/assets/150454622/8d12cb60-f190-4bc5-8e83-fd1d6b88fe78"> 
<img width="456" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/150454622/7b28217f-ae15-4925-8006-94d017ca959e">
I am unable to install msys

**Comment by EnzioKam** [comment] 2024-01-15 07:04
First issue seems to be a duplicate of #2, second issue might a be a problem with downloading from SourceForge (could be due to their server issues or your internet connectivity). Either way, please try out the instructions in my post in #2 and see if it works.

**Comment by ZHD1987E** [comment] 2024-01-15 08:25
I suggest you directly download from this link: https://sourceforge.net/projects/mingwbuilds/

**Comment by Siyi-Xu-Emma** [comment] 2024-01-15 09:17
Not solved for me when I tried to install directly from the link it said cannot download repository.txt

![image](https://github.com/nus-cs2030/2324-s2/assets/139932522/1c8b1cbc-11a5-4309-96ea-40a728955018)

**Comment by ZHD1987E** [comment] 2024-01-15 09:18
I think you will need to change mirrors…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZHD1987E** [comment] 2024-01-16 01:12
...or try doing this command:
`scoop install main/msys`

**Comment by EnzioKam** [comment] 2024-01-17 05:56
Closing the issue since there does not seem to be any more response. Please open a new issue if you still need help.

**Closed by EnzioKam** 2024-01-17 05:56 UTC
