### ISSUE TITLE
Issue with Main class not accessing roster

### ISSUE THREAD

**Issue by delulu04** [nus-cs2030/2324-s2#245] opened 2024-03-19 01:04 UTC
# Summary

I have passed codecrunch level1-5, however when I try to run my Main class, the roster is correctly generated but I cannot access the data using getGrade(). Optional.empty is always returned

Since I have passed 5/6 test cases on cc, I assumed that my design is correct thus far. 

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

        System.out.println(roster); //check if roster is generated correctly
        System.out.println(roster.getGrade("Jack", "CS2030", "Lab4")); 

After adding all the data into the roster, I did ^ to check whether the roster was correctly generated. Output generated is below 

## Screenshots
<img width="894" alt="Screenshot 2024-03-19 at 9 03 12 AM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/8a7044ff-f618-4ff8-8620-4679c11134e0">

Any help is appreciated, thank you!

**Comment by gnimnix** [comment] 2024-03-19 01:42
Hi, please show how u defined your `Main` class and how you implemented `getGrade`.

**Comment by zuoshihua** [comment] 2024-03-19 02:40
Did you reassign your `Roster`?

```java

roster = roster.add("Jack", "CS2040", "Lab4");
```

Since `Roster` is immutable, just performing

```java
roster.add("Jack", "CS2040", "Lab4");
```

will not update `roster`.

**Comment by Gracesong146** [comment] 2024-03-19 04:42
I have the same issue as well. Somehow if i directly key in every single line, it works, but it just doesnt work when I use the scanner to get user input. ive tried bufferedreader as an alternative user input method, still doesnt work :(

**Comment by jarethlee** [comment] 2024-03-19 05:44
The issue definitely lies with `getGrade` in your `Roster` if it is only returning Optional.empty for all queries. You might want to check your implementation again.

**Comment by eleorakow** [comment] 2024-03-19 05:44
getGrade should be returning a String and not an Optional, maybe check how you are implementing getGrade again

**Comment by LMDlifers** [comment] 2024-03-19 17:20
Maybe your getGrade() is not evaluating as intended

**Comment by kee-x** [comment] 2024-03-19 17:24
I think you need to check your getGrade() method, since it is showing that all the records do not exist, I think there is an error in the logic behind the code.

**Comment by hohinnn** [comment] 2024-03-20 07:52
^agree with the rest, definitely an issue with you getGrade() method as it is returning an Optional.empty for all queries and hence returning the orElse value instead

**Comment by clarequek** [comment] 2024-03-21 04:17
The return type of getGrade should be a string and not optional. After you change, the code should be work already

**Comment by delulu04** [comment] 2024-03-21 06:52
I have solved the problem, thank you all!

**Comment by cherylkohzw** [comment] 2024-03-21 10:56
I think you should check your getGrade() method.
Nice to hear that you have solved it

**Comment by ZHD1987E** [comment] 2024-04-11 10:39
@delulu04 

You might want to close this issue since you're done with it...

**Closed** 2024-04-13 02:31 UTC
